# Generated by Django 5.2.3 on 2025-07-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='blog/previews/', verbose_name='Превью')),
                ('creation_at', models.DateField(auto_now_add=True)),
                ('publication_sign', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('number_views', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': '<Блоговая запись>',
                'verbose_name_plural': 'Блоговые записи',
                'ordering': ['-creation_at'],
            },
        ),
    ]
