# Generated by Django 5.2.3 on 2025-07-04 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=150, verbose_name='Категория')),
                ('desc_category', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=150, verbose_name='Продукт')),
                ('desc', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='photos/', verbose_name='Фотография')),
                ('p_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('mod_date', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
                'ordering': ['p_price'],
            },
        ),
    ]
