# Generated by Django 5.2.3 on 2025-10-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_desc_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publication_sign',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
    ]
