# Generated by Django 5.2.3 on 2025-10-06 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_publication_sign'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['p_price'], 'permissions': [('can_unpublish_product', 'Может отменять публикацию продукта')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
