# Generated by Django 5.2.3 on 2025-10-06 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['p_price'], 'permissions': [('can_unpublish_product', 'Может отменять публикацию продукта'), ('can_delete_product', 'Может удалять продукты других пользователей')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
